/**
 * List of style ids that have a preview asset under public/styles/.
 *
 * Every listed id maps to public/styles/<id>.webp and is validated by
 * scripts/check-styles.mjs.
 */
export const STYLE_PREVIEW_IDS: readonly string[] = [
  'classic',
  'bold-ink',
  'hatched-line',
  'line-wash',
  'two-ink',
  'mass-caricature',
  'feature-caricature',
  'reduced-caricature',
  'soft-pastel',
  'flat-colour',
  'opaque-paint',
  'thick-paint',
  'stretched-caricature',
  'wet-paper',
  'single-ink',
  'retro-print',
  'carved-block',
  'wood-block',
  'screen-print',
  'newsprint-caricature',
  'engraved-plate',
  'double-pass',
  'paper-cutout',
  'torn-paper',
  'three-tone-panel',
  'wood-inlay',
  'fabric-applique',
  'modelled-caricature',
  'thread-work',
  'rubber-hose',
  'chibi',
  'saturday-cartoon',
  'toon-3d',
  'comic-strip',
  'die-cut-sticker',
  'kawaii-pastel',
  'ballpoint-doodle',
  'continuous-line',
  'technical-pen',
  'blueprint',
  'graphite-pencil',
  'charcoal',
  'coloured-pencil',
  'oil-pastel',
  'chalk-pastel',
  'wax-crayon',
  'sanguine',
  'chalkboard',
  'oil-glaze',
  'ink-wash',
  'storybook-gouache',
  'airbrush',
  'spray-graffiti',
  'risograph',
  'linocut',
  'cyanotype',
  'origami',
  'quilling',
  'papercraft',
  'magazine-collage',
  'silhouette-cut',
  'knitted',
  'cross-stitch',
  'felt-plush',
  'batik',
  'patchwork-quilt',
  'woven-tapestry',
  'plasticine',
  'porcelain',
  'wood-carving',
  'bronze',
  'marble-bust',
  'vinyl-toy',
  'papier-mache',
  'bobblehead',
  'editorial-cartoon',
  'street-caricature',
  'pop-art',
  'geometric-vector',
  'pixel-art',
  'low-poly',
  'line-icon',
  'neon-sign',
  'duotone-poster',
  'art-nouveau',
  'art-deco',
  'mid-century',
  'ukiyo-e',
  'illuminated-manuscript',
  'ottoman-miniature',
  'travel-poster',
  'psychedelic',
  'mosaic',
  'stained-glass',
  'iznik-tile',
  'fresco',
  'sand-art',
  'ebru',
  'embossed-copper',
  'goofy-sketch',
]

/** Which approved source a style is previewed on (task 0017 section 3.2). */
export type PreviewSubject = 'K' | 'E' | 'P' | 'M' | 'N' | 'C' | 'G' | 'A' | 'Y' | 'S' | 'T' | 'D'

/** The subject of every active style: K woman, E man, P pet, M landscape, N still life. */
export const PREVIEW_SUBJECTS: Readonly<Record<string, PreviewSubject>> = {
  classic: 'K',
  'bold-ink': 'E',
  'hatched-line': 'A',
  'line-wash': 'M',
  'two-ink': 'N',
  'mass-caricature': 'E',
  'feature-caricature': 'A',
  'reduced-caricature': 'E',
  'soft-pastel': 'K',
  'flat-colour': 'K',
  'opaque-paint': 'N',
  'thick-paint': 'M',
  'stretched-caricature': 'Y',
  'wet-paper': 'C',
  'single-ink': 'K',
  'retro-print': 'K',
  'carved-block': 'E',
  'wood-block': 'M',
  'screen-print': 'Y',
  'newsprint-caricature': 'G',
  'engraved-plate': 'C',
  'double-pass': 'G',
  'paper-cutout': 'P',
  'torn-paper': 'Y',
  'three-tone-panel': 'K',
  'wood-inlay': 'N',
  'fabric-applique': 'P',
  'modelled-caricature': 'K',
  'thread-work': 'N',
  'rubber-hose': 'P',
  chibi: 'C',
  'saturday-cartoon': 'M',
  'toon-3d': 'P',
  'comic-strip': 'Y',
  'die-cut-sticker': 'S',
  'kawaii-pastel': 'T',
  'ballpoint-doodle': 'E',
  'continuous-line': 'G',
  'technical-pen': 'N',
  blueprint: 'M',
  'graphite-pencil': 'G',
  charcoal: 'A',
  'coloured-pencil': 'Y',
  'oil-pastel': 'S',
  'chalk-pastel': 'T',
  'wax-crayon': 'D',
  sanguine: 'E',
  chalkboard: 'N',
  'oil-glaze': 'N',
  'ink-wash': 'A',
  'storybook-gouache': 'P',
  airbrush: 'Y',
  'spray-graffiti': 'S',
  risograph: 'A',
  linocut: 'P',
  cyanotype: 'S',
  origami: 'A',
  quilling: 'N',
  papercraft: 'C',
  'magazine-collage': 'T',
  'silhouette-cut': 'E',
  knitted: 'T',
  'cross-stitch': 'M',
  'felt-plush': 'S',
  batik: 'D',
  'patchwork-quilt': 'M',
  'woven-tapestry': 'C',
  plasticine: 'T',
  porcelain: 'D',
  'wood-carving': 'G',
  bronze: 'Y',
  'marble-bust': 'E',
  'vinyl-toy': 'P',
  'papier-mache': 'N',
  bobblehead: 'S',
  'editorial-cartoon': 'K',
  'street-caricature': 'E',
  'pop-art': 'T',
  'geometric-vector': 'D',
  'pixel-art': 'P',
  'low-poly': 'M',
  'line-icon': 'N',
  'neon-sign': 'Y',
  'duotone-poster': 'C',
  'art-nouveau': 'D',
  'art-deco': 'E',
  'mid-century': 'P',
  'ukiyo-e': 'M',
  'illuminated-manuscript': 'A',
  'ottoman-miniature': 'Y',
  'travel-poster': 'C',
  psychedelic: 'K',
  mosaic: 'D',
  'stained-glass': 'K',
  'iznik-tile': 'C',
  fresco: 'A',
  'sand-art': 'M',
  ebru: 'P',
  'embossed-copper': 'G',
  'goofy-sketch': 'G',
}

/** The five approved source images, each with its approved sha256 prefix. */
export const PREVIEW_SOURCES: Readonly<Record<PreviewSubject, { readonly path: string; readonly sha256_prefix: string }>> = {
  K: { path: 'public/hero/before.jpg', sha256_prefix: '1ff634d7f764' },
  E: { path: 'assets/gallery/man-portrait/source.jpg', sha256_prefix: 'ebe1ce07b600' },
  P: { path: 'assets/gallery/pet/source.jpg', sha256_prefix: '3bca2f594279' },
  M: { path: 'assets/gallery/maiden-tower/source.jpg', sha256_prefix: 'e9cbb3dfc64e' },
  N: { path: 'assets/gallery/still-life/source.jpg', sha256_prefix: 'd0ea0b09259c' },
  C: { path: 'assets/subjects/couple/source.jpg', sha256_prefix: '1e3aec217cd4' },
  G: { path: 'assets/subjects/friends/source.jpg', sha256_prefix: 'a43f62a839eb' },
  A: { path: 'assets/subjects/family/source.jpg', sha256_prefix: '1ec1c566e2e8' },
  Y: { path: 'assets/subjects/older-woman/source.jpg', sha256_prefix: 'c3b315ca98c1' },
  S: { path: 'assets/subjects/bearded-man/source.jpg', sha256_prefix: '2d485434c0d3' },
  T: { path: 'assets/subjects/cat/source.jpg', sha256_prefix: '38df2698eb11' },
  D: { path: 'assets/subjects/dog/source.jpg', sha256_prefix: '60ec9b08cde9' },
}

/** The render batches of task 0017 (section 4.4): 12 batches, 92 styles, in order. */
export const PREVIEW_BATCHES: readonly (readonly string[])[] = [
  ['two-ink', 'double-pass', 'screen-print', 'duotone-poster', 'risograph', 'mass-caricature', 'chibi', 'bobblehead', 'street-caricature'],
  ['bold-ink', 'rubber-hose', 'saturday-cartoon', 'toon-3d', 'comic-strip', 'die-cut-sticker', 'kawaii-pastel'],
  ['hatched-line', 'line-wash', 'ballpoint-doodle', 'continuous-line', 'technical-pen', 'blueprint'],
  ['graphite-pencil', 'charcoal', 'coloured-pencil', 'oil-pastel', 'chalk-pastel', 'wax-crayon', 'sanguine', 'chalkboard'],
  ['opaque-paint', 'thick-paint', 'wet-paper', 'oil-glaze', 'ink-wash', 'storybook-gouache', 'airbrush', 'spray-graffiti'],
  ['carved-block', 'wood-block', 'engraved-plate', 'linocut', 'cyanotype'],
  ['paper-cutout', 'torn-paper', 'origami', 'quilling', 'papercraft', 'magazine-collage', 'silhouette-cut'],
  ['fabric-applique', 'thread-work', 'knitted', 'cross-stitch', 'felt-plush', 'batik', 'patchwork-quilt', 'woven-tapestry'],
  ['modelled-caricature', 'plasticine', 'porcelain', 'wood-carving', 'bronze', 'marble-bust', 'vinyl-toy', 'papier-mache'],
  ['reduced-caricature', 'stretched-caricature', 'newsprint-caricature', 'editorial-cartoon', 'pop-art', 'geometric-vector', 'pixel-art', 'low-poly', 'line-icon', 'neon-sign'],
  ['art-nouveau', 'art-deco', 'mid-century', 'ukiyo-e', 'illuminated-manuscript', 'ottoman-miniature', 'travel-poster', 'psychedelic'],
  ['wood-inlay', 'mosaic', 'stained-glass', 'iznik-tile', 'fresco', 'sand-art', 'ebru', 'embossed-copper'],
]

const PREVIEW_DIRS = { web: 'styles-web', full: 'styles' } as const
export type PreviewSize = keyof typeof PREVIEW_DIRS
/** The public URL of a style's preview; the file is 'public' + this. */
export function stylePreviewPath(id: string, size: PreviewSize = 'web'): string {
  return '/' + PREVIEW_DIRS[size] + '/' + id + '.webp'
}
